### ISSUE TITLE
能否设置成下载完一部后立马上传

### ISSUE THREAD

**Issue by lcylty** [horryruo/ikoa-vps#1]
如果提交多部的话，会全部下载完成之后才开始上传。这样的话，只有大盘鸡才能愉快的玩耍了o(╥﹏╥)o
如果设置成下一部就上传一部的话，对vps的硬盘要求就没那么高了

**Comment by horryruo** [comment]
我稍微修改下

**Comment by horryruo** [comment]
> 如果提交多部的话，会全部下载完成之后才开始上传。这样的话，只有大盘鸡才能愉快的玩耍了o(╥﹏╥)o
> 如果设置成下一部就上传一部的话，对vps的硬盘要求就没那么高了

已添加功能，更新后在config设置即可

**Comment by lcylty** [comment]
> > 如果提交多部的话，会全部下载完成之后才开始上传。这样的话，只有大盘鸡才能愉快的玩耍了o(╥﹏╥)o
> > 如果设置成下一部就上传一部的话，对vps的硬盘要求就没那么高了
> 
> 已添加功能，更新后在config设置即可

如果我设置 down_time =2 ，那么就算提交10部电影，在下载完前两部后，任务也会停止
原程序的 down_time 应该控制的是可提交任务数，下多少部上传一次或许另有变量控制

**Comment by horryruo** [comment]
> > > 如果提交多部的话，会全部下载完成之后才开始上传。这样的话，只有大盘鸡才能愉快的玩耍了o(╥﹏╥)o
> > > 如果设置成下一部就上传一部的话，对vps的硬盘要求就没那么高了
> > 
> > 
> > 已添加功能，更新后在config设置即可
> 
> 如果我设置 down_time =2 ，那么就算提交10部电影，在下载完前两部后，任务也会停止
> 原程序的 down_time 应该控制的是可提交任务数，下多少部上传一次或许另有变量控制

有一变量与上传判断有关,它适合于heroku环境但不适合vps环境,我将尝试修改

**Comment by horryruo** [comment]
> > > 如果提交多部的话，会全部下载完成之后才开始上传。这样的话，只有大盘鸡才能愉快的玩耍了o(╥﹏╥)o
> > > 如果设置成下一部就上传一部的话，对vps的硬盘要求就没那么高了
> > 
> > 
> > 已添加功能，更新后在config设置即可
> 
> 如果我设置 down_time =2 ，那么就算提交10部电影，在下载完前两部后，任务也会停止
> 原程序的 down_time 应该控制的是可提交任务数，下多少部上传一次或许另有变量控制

down_time是我加的参数....目前，已添加参数到shell，down_time已可控制下载上传部数，同时，若你的序列码小于45也将上传
