### ISSUE TITLE
monthly_only功能是否没有实现？

### ISSUE THREAD

**Issue by lcylty** [horryruo/ikoa-vps#2]
查看下载日志发现，非月额的影片也下载了。查询快乐码余额，也确实扣除了 (Ｔ▽Ｔ)

id,name,taskid,status,size,bitrate,multipart,tag,monthly
mimk00009,,0,succeed,M,6000kbps,3,,true
mimk00010,,0,succeed,M,6000kbps,3,,true
mimk00011,,0,succeed,M,6000kbps,3,,true
mimk00012,,0,succeed,M,6000kbps,3,,true
mimk00013,,0,succeed,M,6000kbps,2,,true
mimk00014,,0,succeed,M,6000kbps,2,,false
mimk00015,,0,succeed,M,6000kbps,0,,true
mimk00016,,0,succeed,M,6000kbps,0,,true
mimk00017,,0,succeed,M,6000kbps,0,,true
mimk00018,,0,succeed,M,6000kbps,0,,false

**Comment by horryruo** [comment]
少加了个变量，现已修复
