### ISSUE TITLE
下载完成后只上传ikoalogs，不上传视频

### ISSUE THREAD

**Issue by tyhunter** [horryruo/ikoa-vps#4]
config内配置文件如下：
[default]
usedrive = gd
destination_path = /download
log_path = /ikoalogs
adminuser = admin
adminpassword = admin
merge_bool = true
serial_code = ****************
monthly_only = true
output_filename = cid
secret_key = 
runport = 5000
down_time = 5
accounts = sa
[rclone_conf_gd]
team_drive_id = 0****_x70xwrUk9PVA

可以正常执行，但是下载完成后团队盘里只有/ikoalogs文件夹和下面的csv log文件，没有看到视频文件被成功传上来，请教下是哪里配置出错了吗？

**Comment by horryruo** [comment]
目前的判断机制可能刚好downtime那一次ikoa下载失败就上传失败，down_time设置为1试试

**Comment by tyhunter** [comment]
@horryruo 感谢，修改为1后解决了，感觉是不是可以备注下？默认config.ini里面就是5

**Comment by horryruo** [comment]
已经把默认改为1
